Calculating in Twig with integers
bolt/docs pull request #1166
Opened 2021-06-28 08:39 UTC by evertalbers

Following Ivo's tips on https://boltcms.slack.com/archives/C094GL7ME/p1624866867086300

Technically the same could be added to the float field, but float-users will probably see the mention at the integer when scrolling past the options.

2021-06-28 09:19 UTC, bobdenotter approved these changes
Thanks, @evertalbers 👍

2021-06-28 10:17 UTC, evertalbers commented
Oh darn, I think I added this at the wrong location. Looks like this should have gone into https://docs.bolt.cm/4.0/fields/number and not in the end user manual.

2021-07-09 14:07 UTC, bobdenotter approved these changes

2021-07-09 14:08 UTC, bobdenotter requested changes
Ah, right.. Should we close this one, then?

2021-07-09 16:00 UTC, evertalbers commented
Yes, please close it

2021-07-10 05:55 UTC, closed without merging

2021-07-10 05:56 UTC, bobdenotter commented
Done. ;-)