Document creating backend pages
bolt/docs pull request #1185
Opened 2021-08-03 10:20 UTC by I-Valchev

2021-08-03 11:03 UTC, nestordedios requested changes
Nice work @I-Valchev !! 👍  I pointed out some things that you may want to reconsider.

2021-08-03 11:03 UTC, nestordedios commented on docs/extensions/pages.md
> +Controller in the `src` folder of your project.
Hi @I-Valchev , Nice Docs!! 👏 

Maybe the word **Controller** should be capitalized or not capitalized in the entire document to keep it consistent?

2021-08-03 11:03 UTC, nestordedios commented on docs/extensions/pages.md
> +* The controller class needs to implement the `BackendZoneInterface`
See here the word **controller** not being capitalized

2021-08-03 11:03 UTC, nestordedios commented on docs/extensions/pages.md
> +        // folder in the root of your project.
Maybe that could be wrapped in a block comment?
```
    /**
     * content_user.html.twig is a custom file
     * that needs to be located in the `templates`
     * folder in the root of your project.
     */
```

2021-08-03 11:03 UTC, nestordedios commented on docs/extensions/pages.md
> +Localte the `config/routes.yaml` file and add the following **after**
**Localte** looks like a typo here

2021-08-03 11:25 UTC, I-Valchev commented on docs/extensions/pages.md
> +Controller in the `src` folder of your project.
Yes, good idea! I've capitalised them.

2021-08-03 11:28 UTC, I-Valchev commented on docs/extensions/pages.md
> +        // folder in the root of your project.
The `/**` annotation is used for PhpDoc (e.g. to document functions, classes). In that case, this is more like a comment for the person copy-pasting the example.

2021-08-03 11:30 UTC, I-Valchev commented on docs/extensions/pages.md
> +Localte the `config/routes.yaml` file and add the following **after**
Yes, good catch. I type like a monkey 🙈

2021-08-03 11:51 UTC, nestordedios commented on docs/extensions/pages.md
> +Controller in the `src` folder of your project.
Perfect! 👍

2021-08-03 11:52 UTC, nestordedios commented on docs/extensions/pages.md
> +        // folder in the root of your project.
Ah ok. I always though that block comments where also meant to comment out paragraphs of text. In that case, I haven't said anything 🙈

2021-08-03 11:55 UTC, nestordedios approved these changes
It looks great! 👍 This is ready for consumption.

2021-08-18 12:05 UTC, merged

2021-08-18 12:07 UTC, bobdenotter commented
Part of #1168