New update
bolt/docs pull request #1188
Opened 2021-08-19 10:05 UTC by mcdennem

2021-08-19 13:58 UTC, nestordedios requested changes
Nice @mcdennem 👍 . I have pointed out some things that might need some changes.

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/paragraph.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/paragraph.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_filter.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_get.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_get_all.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_grep.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_match.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_quote.md
> +composer require jasny/twig-extensions
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_replace.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_split.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/product.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/sum.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/truncate.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/values.md
> +Jasny's Twig Extensions can be easily installed using composer:
Since we refer to the technology maybe we should capitalize `composer` to look like `Composer`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_filter.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_get.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_get_all.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_grep.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_match.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_quote.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_replace.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_split.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/product.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/sum.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/truncate.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/values.md
> +To use in a symfony project register the extensions as a service:
Since we refer to the technology maybe we should capitalize `symfony` to look like `Symfony`?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/preg_split.md
> +`preg_split(pattern)` is a Twig filter to make PHPs preg_split() function available as twig filter. It splits text into
Maybe here `twig` (twig filter) should be capitalized as well (Twig filter)?

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/related_content.md
> +`related_content(content, name = null, bidirectional = true, limit = null, publishedOnly = true)` is a Twig function to
Could it be there is text missing here? It seems there is no description added for this Twig function.

2021-08-19 13:58 UTC, nestordedios commented on docs/twig-components/method/title.md
>  `title(locale = "", length = 120)` is a Twig filter to ...
is a Twig filter to ... should be removed and keep the description below or continue after the name of the function

2021-08-20 09:04 UTC, mcdennem commented on docs/twig-components/method/related_content.md
> +`related_content(content, name = null, bidirectional = true, limit = null, publishedOnly = true)` is a Twig function to
It has a link to another page.

2021-08-20 13:01 UTC, nestordedios reviewed
Thanks @mcdennem !! There is only one thing on the relate_content.md file that is not clear to me.

2021-08-20 13:01 UTC, nestordedios commented on docs/twig-components/method/related_content.md
> +`related_content(content, name = null, bidirectional = true, limit = null, publishedOnly = true)` is a Twig function to
Yes I see the link after the text but is it the intention that it reads like **`related_content(content, name = null, bidirectional = true, limit = null, publishedOnly = true)` is a Twig function to ...** (see line 4), but there is no description about what the function does?

2021-08-20 13:24 UTC, mcdennem commented on docs/twig-components/method/related_content.md
> +`related_content(content, name = null, bidirectional = true, limit = null, publishedOnly = true)` is a Twig function to
Ah, sure, I deleted the "is a Twig function to..."

2021-08-20 13:37 UTC, nestordedios approved these changes
Great!! Nice job @mcdennem 👍

2021-08-20 13:38 UTC, nestordedios commented on docs/twig-components/method/related_content.md
> +`related_content(content, name = null, bidirectional = true, limit = null, publishedOnly = true)` is a Twig function to
Thank you! 👍

2021-08-20 13:43 UTC, merged